language: python
sudo: false
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"

install:
 - "pip install -r requirements.txt"

script:
 - "cookiecutter --no-input ."
 - "cd pypt"
 - "py.test --cov pypt --cov-report term-missing tests/"

notifications:
  email:
    on_success: always
    on_failure: always
